apps/sso/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import application
from .views import onetimemessage
from .views import password_change, password_change_done, logout, profile, contact, delete_profile
from .views import password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from .views import emails, confirm_email, password_create_confirm, password_create_complete
from .views import organisation

urlpatterns = [
    url(r'^$', application.UserList.as_view(), name='user_list'),
    url(r'^me/$', profile, name='profile'),
    url(r'^add/$', application.add_user, name='add_user'),
    url(r'^add/done/(?P<uuid>[^/]+)/$', application.add_user_done, name="add_user_done"),
    url(r'^(?P<uuid>[a-z0-9]{32})/$', application.update_user, name="update_user"),
    url(r'^(?P<uuid>[a-z0-9]{32})/delete/$', application.UserDeleteView.as_view(), name="delete_user"),
    url(r'^app_admin/$', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    url(r'^app_admin/(?P<uuid>[a-z0-9]{32})/', application.app_admin_update_user, name="app_admin_update_user"),
    url(r'^logout/$', logout, name='logout'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^contact_thanks/$', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    url(r'^email/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email, name='confirm_email'),
    url(r'^emails/$', emails, name='emails'),
    url(r'^profile/delete/$', delete_profile, name='delete_profile'),
    url(r'^password_change/$', password_change, name='password_change'),
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password_resend/done/$', TemplateView.as_view(template_name="accounts/password_resend_done.html"), name='password_resend_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^create/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_create_confirm, name='password_create_confirm'),
    url(r'^create/done/(?P<uidb64>[0-9A-Za-z_\-]+)/$', password_create_complete, name='password_create_complete'),
    url(r'^organisation_change/(?P<pk>\d+)/$', organisation.OrganisationChangeDetailView.as_view(), name='organisationchange_detail'),
    url(r'^organisation_change/me/$', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    url(r'^organisation_change/$', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    url(r'^organisation_change/(?P<pk>\d+)/accept/$', organisation.OrganisationChangeAcceptView.as_view(), name='organisationchange_accept'),
    url(r'^messages/(?P<uuid>[^/]+)/$', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/api/urls.py
from django.conf.urls import url
from sso.api.views import users, users_v2, organisations, home, countries, regions, country_groups, media
 
urlpatterns = [
    url(r'^$', home.home, name='home'),
    url(r'^user_emails/$', users_v2.user_emails, name='user_emails'),
    url(r'^v1/users/$', users.get_user_list, name='v1_users'),
    url(r'^v1/users/me/$', users.UserDetailView.as_view(), name='v1_users_me'),
    url(r'^v1/users/(?P<uuid>[a-z0-9]{32})/$', users.UserDetailView.as_view(), name='v1_user'),
    url(r'^v1/users/me/apps/$', users.UserDetailView.as_view(is_apps_only=True), name='v1_users_my_apps'),
    url(r'^v1/users/(?P<uuid>[a-z0-9]{32})/apps/$', users.UserDetailView.as_view(is_apps_only=True), name='v1_users_apps'),
    url(r'^v2/users/$', users_v2.UserList.as_view(), name='v2_users'),
    url(r'^v2/users/me/$', users_v2.MyDetailView.as_view(), name='v2_users_me'),
    url(r'^v2/users/(?P<uuid>[a-z0-9]{32})/$', users_v2.UserDetailView.as_view(), name='v2_user'),
    url(r'^v2/users/me/navigation/$', users_v2.MyGlobalNavigationView.as_view(), name='v2_navigation_me'),
    url(r'^v2/users/(?P<uuid>[a-z0-9]{32})/navigation/$', users_v2.GlobalNavigationView.as_view(), name='v2_navigation'),
    url(r'^v2/organisations/$', organisations.OrganisationList.as_view(), name='v2_organisations'),
    url(r'^v2/organisations/(?P<uuid>[a-z0-9]{32})/$', organisations.OrganisationDetailView.as_view(), name='v2_organisation'),
    url(r'^v2/countries/$', countries.CountryList.as_view(), name='v2_countries'),
    url(r'^v2/countries/(?P<iso2_code>[A-Z]{2})/$', countries.CountryDetailView.as_view(), name='v2_country'),
    url(r'^v2/regions/$', regions.RegionList.as_view(), name='v2_regions'),
    url(r'^v2/regions/(?P<uuid>[a-z0-9]{32})/$', regions.RegionDetailView.as_view(), name='v2_region'),
    url(r'^v2/country_groups/$', country_groups.CountryGroupList.as_view(), name='v2_country_groups'),
    url(r'^v2/country_groups/(?P<uuid>[a-z0-9]{32})/$', country_groups.CountryGroupDetailView.as_view(), name='v2_country_group'), 
    url(r'^v2/users/me/picture/$', media.MyUserPictureDetailView.as_view(), name='v2_picture_me'),
    url(r'^v2/users/(?P<uuid>[a-z0-9]{32})/picture/$', media.UserPictureDetailView.as_view(), name='v2_picture'),
]

apps/sso/auth/urls.py
from django.conf.urls import url
from sso.auth.views import LoginView, TokenView
from sso.auth.views.profile import ProfileView, TOTPSetup, PhoneSetupView, AddPhoneView, AddU2FView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^token/(?P<device_id>[\d]+)/(?P<user_data>[^/]+)/$', TokenView.as_view(), name='token'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/totp_setup/$', TOTPSetup.as_view(), name='profile_totp_setup'),
    url(r'^profile/add_phone/$', AddPhoneView.as_view(), name='add_phone'),
    url(r'^profile/phone_setup/(?P<sms_device_id>[\d]+)/$', PhoneSetupView.as_view(), name='phone_setup'),
    url(r'^profile/u2f/add_device/$', AddU2FView.as_view(), name='u2f_add_device'),
]

apps/sso/emails/urls.py
from django.conf.urls import url
from sso.emails import views
 
urlpatterns = [
    url(r'^group/$', views.GroupEmailList.as_view(), name='groupemail_list'), 
    url(r'^group/(?P<uuid>[a-z0-9]{32})/$', views.GroupEmailDetailView.as_view(), name='groupemail_detail'),
    url(r'^group/(?P<uuid>[a-z0-9]{32})/update/$', views.GroupEmailUpdateView.as_view(), name='groupemail_update'),
    url(r'^group/add/$', views.GroupEmailCreateView.as_view(), name='groupemail_create'),
    url(r'^group/(?P<uuid>[a-z0-9]{32})/forward/add/$', views.GroupEmailForwardCreateView.as_view(), name='emailforward_create'),
    url(r'^group/(?P<uuid>[a-z0-9]{32})/forward/(?P<pk>\d+)/$', views.GroupEmailForwardDeleteView.as_view(), name="emailforward_confirm_delete"),
]

apps/sso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import javascript_catalog
from django.conf.urls.static import static
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.registration.sites import RegistrationSite
from sso.admin import sso_admin_site
from sso.views import home
from sso.oauth2.views import openid_configuration

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

js_info_dict = {
    'packages': ('sso',),
}

urlpatterns = [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^admin/', include(sso_admin_site.urls)),
    url(r'^$', home, name='home'),
    url(r'^privacy/$', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    url(r'^about/$', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    url(r'^accounts/', include('sso.auth.urls', namespace="auth")),
    url(r'^accounts/', include('sso.accounts.urls', namespace="accounts")),
    url(r'^accounts/', include(registration_site.urls)),
    url(r'^organisations/', include('sso.organisations.urls', namespace="organisations")),
    url(r'^emails/', include('sso.emails.urls', namespace="emails")),
    url(r'^oauth2/', include('sso.oauth2.urls', namespace="oauth2")),
    url(r'^.well-known/openid-configuration', openid_configuration, name='openid-configuration'),
    url(r'^api/', include('sso.api.urls', namespace="api")),
    url(r'^chained_filter/(?P<app>l10n)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain, name='chained_filter'),
    url(r'^chained_filter/(?P<app>organisations)/(?P<model>AdminRegion)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain,
        kwargs={'manager': 'active_objects'}, name='chained_filter'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sso/forms/fields.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _

from django.forms import fields
from sso.accounts.models import UserManager
from sso.forms import bootstrap


class EmailFieldLower(fields.EmailField):
    widget = bootstrap.EmailInput(attrs={'size': 50})
    
    def to_python(self, value):
        email = super(EmailFieldLower, self).to_python(value).rstrip().lstrip()
        return UserManager.normalize_email(email)
    
    def __init__(self, max_length=None, min_length=None, *args, **kwargs):
        if 'label' not in kwargs:
            kwargs['label'] = _('email address')
        super(EmailFieldLower, self).__init__(max_length=max_length, min_length=min_length, *args, **kwargs)

apps/sso/accounts/views/filter.py
# -*- coding: utf-8 -*-
import logging

from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from l10n.models import Country
from sso.views.generic import SearchFilter, ViewChoicesFilter, ViewQuerysetFilter
from sso.accounts.models import ApplicationRole, RoleProfile
from sso.organisations.models import AdminRegion, Organisation


logger = logging.getLogger(__name__)


class UserSearchFilter(SearchFilter):
    search_names = ['username__icontains', 'first_name__icontains', 'last_name__icontains', 'useremail__email__icontains']


class IsActiveFilter(ViewChoicesFilter):
    name = 'is_active'
    choices = (('1', _('Active Users')), ('2', _('Inactive Users')))
    select_text = _('active/inactive')
    select_all_text = _("All")

    def map_to_database(self, value):
        return True if (value.pk == "1") else False


class CountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisations__country'
    model = Country
    filter_list = Country.objects.filter(organisation__isnull=False).distinct()
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region,center'
    remove = 'admin_region,center,app_role,role_profile,p'


class AdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisations__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = 'center'
    remove = 'center,app_role,role_profile,p'


class CenterFilter(ViewQuerysetFilter):
    name = 'center'
    qs_name = 'organisations'
    model = Organisation
    select_text = _('Organisation')
    select_all_text = _('All Organisations')
    remove = 'app_role,p'


class ApplicationRoleFilter(ViewQuerysetFilter):
    name = 'app_role'
    model = ApplicationRole
    select_text = _('Role')
    select_all_text = _('All Roles')

    def apply(self, view, qs, default=''):
        """
        filter with respect to application_roles and role_profiles
        """
        value = self.get_value_from_query_param(view, default)
        if value:
            q = Q(application_roles=value)
            q |= Q(role_profiles__application_roles=value)
            qs = qs.filter(q)
        setattr(view, self.name, value)
        return qs


class RoleProfileFilter(ViewQuerysetFilter):
    name = 'role_profile'
    qs_name = 'role_profiles'
    model = RoleProfile
    select_text = _('Profile')
    select_all_text = _('All Profiles')


########################################################################################
# organisationchange list filter


class OrganisationChangeCountryFilter(ViewQuerysetFilter):
    name = 'country'
    qs_name = 'organisation__country'
    model = Country
    filter_list = Country.objects.filter(organisation__isnull=False).distinct()
    select_text = _('Country')
    select_all_text = _('All Countries')
    all_remove = 'admin_region'
    remove = 'admin_region,p'


class OrganisationChangeAdminRegionFilter(ViewQuerysetFilter):
    name = 'admin_region'
    qs_name = 'organisation__admin_region'
    model = AdminRegion
    select_text = _('Region')
    select_all_text = _('All Regions')
    all_remove = ''
    remove = 'p'

apps/sso/accounts/views/onetimemessage.py
# -*- coding: utf-8 -*-
import logging

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.utils.decorators import method_decorator

from sso.accounts.models import OneTimeMessage

logger = logging.getLogger(__name__)


class OneTimeMessageView(DetailView):
    model = OneTimeMessage
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            raise PermissionDenied()
        
        self.object.delete()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

apps/sso/api/views/countries.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.db.models import Q
from sso.utils.url import base_url
from sso.utils.parse import parse_datetime_with_timezone_support
from sso.organisations.models import OrganisationCountry
from sso.api.views.generic import JsonListView, JsonDetailView

import logging

logger = logging.getLogger(__name__)


class CountryMixin(object):
    model = OrganisationCountry

    def get_object_data(self, request, obj, details=False):
        base = base_url(request)
        data = {
            '@id': "%s%s" % (base, reverse('api:v2_country', kwargs={'iso2_code': obj.country.iso2_code})),
            'id': u'%s' % obj.uuid.hex,
            'code': obj.country.iso2_code,
            'name': u'%s' % str(obj),
            'email': u'%s' % obj.email,
            'homepage': obj.homepage,
            'last_modified': obj.get_last_modified_deep(),
            'continent': {
                'code': obj.country.continent,
                'name': obj.country.get_continent_display(),
            }
        }
        if details:
            if ('users' in request.scopes) and (obj.country in request.user.get_administrable_user_countries()):
                data['users'] = "%s%s?country=%s" % (base, reverse('api:v2_users'), obj.country.iso2_code)
            if obj.country.organisation_set.exists():
                data['organisations'] = "%s%s?country=%s" % (base, reverse('api:v2_organisations'), obj.country.iso2_code)
            if obj.country.adminregion_set.exists():
                data['regions'] = "%s%s?country=%s" % (base, reverse('api:v2_regions'), obj.country.iso2_code)
            if obj.country_groups.all().exists():
                data['country_groups'] = "%s%s?country=%s" % (base, reverse('api:v2_country_groups'), obj.country.iso2_code)
        return data
  

class CountryDetailView(CountryMixin, JsonDetailView):
    slug_field = 'country__iso2_code'
    slug_url_kwarg = 'iso2_code'
    http_method_names = ['get', 'options']
    operations = {}
    
    def get_queryset(self):
        return super(CountryDetailView, self).get_queryset().prefetch_related('country', 'email')

    def get_object_data(self, request, obj):
        return super(CountryDetailView, self).get_object_data(request, obj, details=True)


class CountryList(CountryMixin, JsonListView):

    def get_queryset(self):
        qs = super(CountryList, self).get_queryset().filter(is_active=True).prefetch_related('country', 'email')
        name = self.request.GET.get('q', None)
        if name:
            qs = qs.filter(country__name__icontains=name)
            
        country_group_id = self.request.GET.get('country_group_id', None)
        if country_group_id:
            qs = qs.filter(country_groups__uuid=country_group_id)

        modified_since = self.request.GET.get('modified_since', None)
        if modified_since:  # parse modified_since
            parsed = parse_datetime_with_timezone_support(modified_since)
            if parsed is None:
                raise ValueError("can not parse %s" % modified_since)
            qs = qs.filter(Q(last_modified__gte=parsed) | Q(country__last_modified__gte=parsed) )

        return qs

apps/sso/templates/include/_base64_picture_field.html
{% load i18n %}

<div id="base64-image" class="form-group form-group-file {% if field.errors %}has-error{% endif %}"
     data-max-size="250px" data-max-file-size="{{ max_file_size }}">
    <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
    <div class="dwbn-form-control">
        <div>
            <img class="img-thumbnail" style="width: 240px; height: 240px;"/>
        </div>
            <div class="btn btn-default btn-file">
                <span class="">{% trans 'Select image' %}</span>
                <input type="file" name="_dummy">
                {{ field }}
            </div>
            <a href="#" class="btn btn-default btn-remove hidden">{% trans 'Remove' %}</a>
            <span class="help-block-file help-block">{% if field.help_text or field.errors %}{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}{% endif %}</span>
    </div>
</div>

apps/sso/templates/include/_field.html
{% if field %}
<div class="form-group {% if field.errors %}has-error{% endif %} {% if field.is_hidden %}dwbn-honeypot{% endif %}">
  <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label> 
  <div class="dwbn-form-control">   
      {{ field }}{% if field.help_text or field.errors %}<span class="help-block">{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}</span>{% endif %}
  </div>
</div>
{% endif %}

apps/sso/templates/include/_list_filter_button.html
{% load list %}
{% if filter.value %}
<a type="button" class="btn btn-default active"  href="{% query_string cl filter.param_name '' %}">{{ filter.select_text }}</a>
{% else %}
<a type="button" class="btn btn-default" href="{% query_string cl filter.param_name '1' filter.remove %}">{{ filter.select_text }}</a>
{% endif %}        

apps/sso/templates/include/_picture_field.html
{% load thumbnail %}
<div class="form-group  {% if field.errors %}has-error{% endif %}">
  <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}{% if field.field.required %}*{% endif %}</label>
  <div class="dwbn-form-control">
      {{ field }}{% if field.help_text or field.errors %}<span class="help-block">{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}</span>{% endif %}
  </div>
</div>

apps/sso/templates/include/_search_form.html
{% load i18n %}
<form class="" method="get">
    {% for key, value in cl.params.items %}
        {% if key != search_var and key != page_var %}
           <input type="hidden" name="{{ key }}" value="{{ value }}">          
        {% endif %}
    {% endfor %}
    <div class="input-group">
        <input type="text" class="form-control" name="{{ search_var }}" value="{{ query }}" placeholder="{% trans 'search text' %}">
        <span class="input-group-btn">
          <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search"></span></button>
        </span>
    </div>
</form>
    

apps/sso/templates/include/_static.html
<div class="form-group">
  <label class="control-label">{{ label }}</label> 
  <div class="dwbn-form-control">
       <p class="form-control-static">{{ valued|default_if_none:"" }}</p>
  </div>
</div>

apps/sso/templates/include/_static_base64_picture_field.html
<div id="base64-image" class="form-group {{ extra_class }}" data-max-size="250px" >
    <label class="control-label">{{ field.label }}</label>
    <div class="dwbn-form-control">
        <p class="form-control-static">
            <img class="img-thumbnail" style="width: 240px; height: 240px;"/>
        </p>
    </div>
</div>
<script>
    $(function () {
        var max_size = $('#base64-image').data("max-size");
        // initialize the img field from base64 data if available
        if ($('[name="base64_picture"]').val()) {
            var style = 'max-height: ' + max_size + '; max-width: ' + max_size + ';'
            $('#base64-image img').replaceWith('<img src="' + $('[name="base64_picture"]').val() + '" alt="Image preview" class="img-thumbnail" style="' + style + '">');
        }
    });
</script>

apps/sso/templates/include/_static_choice_field.html
{% load form %}
<div class="form-group">
  <label class="control-label">{{ field.label }}</label> 
  <div class="dwbn-form-control">
       <p class="form-control-static">
       {{ field.form|selected_choice:field.name }}
  </div>
</div>

apps/sso/templates/include/_static_field.html
<div class="form-group {{ extra_class }}">
  <label class="control-label" >{{ field.label }}</label>
  <div class="dwbn-form-control">
       <p class="form-control-static">{{ field.value|default_if_none:"" }}</p>
  </div>
</div>

apps/sso/templates/include/_static_google_maps_field.html
{% load i18n %}
{% if field.value %}
<div class="form-group">
  <label class="control-label">{{ field.label }}</label> 
  <div class="dwbn-form-control">
       <p class="form-control-static">{% if field.value %}<a href="{{ field.value }}">{% trans 'Google Maps' %} <span class="glyphicon glyphicon-map-marker"></span></a>{% endif %}</p>
  </div>
</div>
{% endif %}

apps/sso/templates/include/_static_picture_field.html
{% load i18n thumbnail %}
<div class="form-group">
    <label class="control-label">{% trans 'picture' %}</label>

    <div class="dwbn-form-control">
        {% thumbnail field "240x240" crop="center" as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">{% endthumbnail %}
    </div>
</div>

apps/sso/templates/include/_user_field.html
{% load i18n %}
<div class="form-group {% if field.errors %}error{% endif %}">
    <label class="control-label" for="id_{{ field.html_name }}">{{ field.label }}</label>    
    <div class="dwbn-form-control">
        {% if field.value %}
        <div class="input-group">
	        {{ field }}
            <span class="input-group-btn">
                <a href="mailto:{{ field.value.primary_email }}" target="_blank" class="btn btn-default" type="button">
                    <i class="glyphicon glyphicon-envelope" title="{% trans 'Send email' %}"></i>
                </a>
            </span>
        </div>
        {% else %}{{ field }}{% endif %}
        {% if field.help_text or field.errors %}<span class="help-block">{{ field.help_text }} {% for error in field.errors %}{{ error }} {% endfor %}</span>{% endif %}
    </div>
</div>

apps/sso/templates/include/fieldset.html
<div class="original">
   {% spaceless %}
   {% for field in inline_form %}
        {% if field.is_hidden %} {{ field }} {% endif %}
   {% endfor %}
   {% endspaceless %}
</div>

{% for field in inline_form.visible_fields %}{% if field.name != "DELETE" %}
    {% include 'include/_field.html' %}
{% endif %}{% endfor %}

apps/sso/templates/include/global_navigation.html
{% load  i18n thumbnail %}
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">{% block brand %}{{ brand }}{% endblock %}</a>
        </div>
        <div class="collapse navbar-collapse">
            {% if user.is_authenticated %}
	            <ul class="nav navbar-nav">
	            {% with user_apps=user.get_global_navigation_urls %}
		            {% if user_apps|length < 5 %}
			            {% for app in user_apps %}
			                <li><a href="{{ app.url }}">{{ app.title }}</a></li>
			            {% endfor %}
		            {% else %}
			            {% for app in user_apps|slice:":3" %}
			                <li><a href="{{ app.url }}">{{ app.title }}</a></li>
			            {% endfor %}
			            {% for app in user_apps|slice:"3:" %}
			                {% if forloop.first %}
			                <li class="dropdown">
			                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'More' %} <b class="caret"></b></a>
			                   <ul class="dropdown-menu">
			                {% endif %}
			                       <li><a href="{{ app.url }}">{{ app.title }}</a></li>
			                {% if forloop.last %}
			                  </ul>
			                </li>
			                {% endif %}
			            {% endfor %}
		            {% endif %}
	            {% endwith %}
	            </ul>
            {% endif %}
            <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'accounts:profile' %}">{% if user.picture %}{% thumbnail user.picture "30x30" crop="center" as im %}<img class="dwbn-icon-user" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="">{% endthumbnail %}{% else %}<i class="glyphicon glyphicon-user"></i>{% endif %} {{ user.first_name }}{% if user.is_verified %} <sup><i class="glyphicon glyphicon-star-empty" title="{% trans '2 factor logged in' %}"></i></sup>{% endif %}</a></li>
                <li><a href="{% url 'accounts:logout' %}"><i class="glyphicon glyphicon-log-out"></i> {% trans 'Log out' %}</a></li>
            {% else %}
                <li><a  href="{% url 'auth:login' %}"><i class="glyphicon glyphicon-log-in"></i> {% trans 'Log in' %}</a></li>
            {% endif %}
            </ul><!-- /.navbar-right -->
        </div><!--/.navbar-collapse -->
    </div>
</div>
<noscript>
    <div class="alert alert-warning">
        {% blocktrans with "http://enable-javascript.com/" as url %}Please activate JavaScript to enable all features. <a href="{{ url }}" target="_blank">Read this page for more help</a>{% endblocktrans %}
	</div>
</noscript>