apps/sso/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import application
from .views import onetimemessage
from .views import password_change, password_change_done, logout, profile, contact, delete_profile
from .views import password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from .views import emails, confirm_email, password_create_confirm, password_create_complete
from .views import organisation

urlpatterns = [
    url(r'^$', application.UserList.as_view(), name='user_list'),
    url(r'^me/$', profile, name='profile'),
    url(r'^add/$', application.add_user, name='add_user'),
    url(r'^add/done/(?P<uuid>[^/]+)/$', application.add_user_done, name="add_user_done"),
    url(r'^(?P<uuid>[a-z0-9]{32})/$', application.update_user, name="update_user"),
    url(r'^(?P<uuid>[a-z0-9]{32})/delete/$', application.UserDeleteView.as_view(), name="delete_user"),
    url(r'^app_admin/$', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    url(r'^app_admin/(?P<uuid>[a-z0-9]{32})/', application.app_admin_update_user, name="app_admin_update_user"),
    url(r'^logout/$', logout, name='logout'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^contact_thanks/$', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    url(r'^email/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email, name='confirm_email'),
    url(r'^emails/$', emails, name='emails'),
    url(r'^profile/delete/$', delete_profile, name='delete_profile'),
    url(r'^password_change/$', password_change, name='password_change'),
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password_resend/done/$', TemplateView.as_view(template_name="accounts/password_resend_done.html"), name='password_resend_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^create/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_create_confirm, name='password_create_confirm'),
    url(r'^create/done/(?P<uidb64>[0-9A-Za-z_\-]+)/$', password_create_complete, name='password_create_complete'),
    url(r'^organisation_change/(?P<pk>\d+)/$', organisation.OrganisationChangeDetailView.as_view(), name='organisationchange_detail'),
    url(r'^organisation_change/me/$', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    url(r'^organisation_change/$', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    url(r'^organisation_change/(?P<pk>\d+)/accept/$', organisation.OrganisationChangeAcceptView.as_view(), name='organisationchange_accept'),
    url(r'^messages/(?P<uuid>[^/]+)/$', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import javascript_catalog
from django.conf.urls.static import static
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.registration.sites import RegistrationSite
from sso.admin import sso_admin_site
from sso.views import home
from sso.oauth2.views import openid_configuration

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

js_info_dict = {
    'packages': ('sso',),
}

urlpatterns = [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^admin/', include(sso_admin_site.urls)),
    url(r'^$', home, name='home'),
    url(r'^privacy/$', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    url(r'^about/$', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    url(r'^accounts/', include('sso.auth.urls', namespace="auth")),
    url(r'^accounts/', include('sso.accounts.urls', namespace="accounts")),
    url(r'^accounts/', include(registration_site.urls)),
    url(r'^organisations/', include('sso.organisations.urls', namespace="organisations")),
    url(r'^emails/', include('sso.emails.urls', namespace="emails")),
    url(r'^oauth2/', include('sso.oauth2.urls', namespace="oauth2")),
    url(r'^.well-known/openid-configuration', openid_configuration, name='openid-configuration'),
    url(r'^api/', include('sso.api.urls', namespace="api")),
    url(r'^chained_filter/(?P<app>l10n)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain, name='chained_filter'),
    url(r'^chained_filter/(?P<app>organisations)/(?P<model>AdminRegion)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain,
        kwargs={'manager': 'active_objects'}, name='chained_filter'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sso/accounts/models.py
# -*- coding: utf-8 -*-
import logging
import re
import uuid
from itertools import chain

from django.db.utils import IntegrityError
from sorl import thumbnail

from current_user.models import CurrentUserField
from django.conf import settings
from django.contrib.auth.models import Group, Permission, \
    PermissionsMixin, AbstractBaseUser, BaseUserManager
from django.core import validators
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from l10n.models import Country
from sso.decorators import memoize
from sso.emails.models import GroupEmailManager
from sso.models import AbstractBaseModel, AddressMixin, PhoneNumberMixin, ensure_single_primary, get_filename, CaseInsensitiveEmailField
from sso.organisations.models import AdminRegion, Organisation
from sso.registration.models import RegistrationProfile
from sso.signals import default_roles
from sso.utils.email import send_mail

logger = logging.getLogger(__name__)


# SUPERUSER_ROLE = 'Superuser'
# STAFF_ROLE = 'Staff'
# USER_ROLE = 'User'


class ApplicationManager(models.Manager):
    def get_by_natural_key(self, uuid):
        return self.get(uuid=uuid)


class Application(models.Model):
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    title = models.CharField(max_length=255)
    url = models.URLField(max_length=2047, blank=True)
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=True)
    global_navigation = models.BooleanField(_('global navigation'),
                                            help_text=_('Designates whether this application should be shown in the global navigation bar.'), default=True)
    is_active = models.BooleanField(_('active'), default=True, help_text=_('Designates whether this application should be provided.'))
    redirect_to_after_first_login = models.BooleanField(_('redirect to after first login'), default=False,
                                                        help_text=_('Designates whether the user should redirected to this app after the first login.'))
    notes = models.TextField(_("Notes"), blank=True, max_length=2048)
    objects = ApplicationManager()
    
    class Meta:
        ordering = ['order', 'title']
        verbose_name = _("application")
        verbose_name_plural = _("applications")
        
    def link(self):
        if self.url:
            return u'<a href="%s">%s</a>' % (self.url, self.title)
        else:
            return ''
    link.allow_tags = True

    def natural_key(self):
        return self.uuid,

    def __unicode__(self):
        return u"%s" % self.title


class RoleManager(models.Manager):
    def get_by_natural_key(self, name):
        return self.get(name=name)


class Role(models.Model):
    name = models.CharField(_("name"), unique=True, max_length=255)
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    group = models.ForeignKey(Group, blank=True, null=True, help_text=_('Associated group for SSO internal permission management.'))
    objects = RoleManager()
    
    class Meta:
        ordering = ['order', 'name']    
        verbose_name = _('role')
        verbose_name_plural = _('roles')

    def natural_key(self):
        return self.name,

    def __unicode__(self):
        return u"%s" % self.name
    

class ApplicationRoleManager(models.Manager):
    def get_by_natural_key(self, uuid, name):
        return self.get(application__uuid=uuid, role__name=name)


class ApplicationRole(models.Model):
    application = models.ForeignKey(Application)
    role = models.ForeignKey(Role)
    is_inheritable_by_org_admin = models.BooleanField(_('inheritable by organisation admin'), default=True,
                                                      help_text=_('Designates that the role can inherited by a organisation admin.'))
    is_inheritable_by_global_admin = models.BooleanField(_('inheritable by global admin'), default=True,
                                                         help_text=_('Designates that the role can inherited by a global admin.'))
    is_organisation_related = models.BooleanField(_('organisation related'), default=False,
                                                  help_text=_('Designates that the role will be deleted in case of a change of the organisation.'))

    objects = ApplicationRoleManager()
     
    class Meta:
        ordering = ['application', 'role']
        unique_together = (("application", "role"),)
        verbose_name = _('application role')
        verbose_name_plural = _('application roles')
    
    def natural_key(self):
        return self.application.natural_key() + self.role.natural_key()
    
    def __unicode__(self):
        return u"%s - %s" % (self.application, self.role)


class RoleProfile(AbstractBaseModel):
    name = models.CharField(_("name"), max_length=255)
    application_roles = models.ManyToManyField(ApplicationRole, help_text=_('Associates a group of application roles that are usually assigned together.'))
    order = models.IntegerField(default=0, help_text=_('Overwrites the alphabetic order.'))
    is_inheritable_by_org_admin = models.BooleanField(_('inheritable by organisation admin'), default=True,
                                                      help_text=_('Designates that the role profile can inherited by a organisation admin.'))
    is_inheritable_by_global_admin = models.BooleanField(_('inheritable by global admin'), default=True,
                                                         help_text=_('Designates that the role profile can inherited by a global admin.'))

    class Meta(AbstractBaseModel.Meta):
        ordering = ['order', 'name']
        verbose_name = _('role profile')
        verbose_name_plural = _('role profiles')
    
    def __unicode__(self):
        return u"%s" % self.name


class UserEmail(AbstractBaseModel):
    MAX_EMAIL_ADRESSES = 2
    email = CaseInsensitiveEmailField(_('email address'), max_length=254, unique=True)
    confirmed = models.BooleanField(_('confirmed'), default=False)
    primary = models.BooleanField(_('primary'), default=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('email address')
        verbose_name_plural = _('email addresses')
        ordering = ['email']

    def __unicode__(self):
        return u"%s" % self.email


class UserManager(BaseUserManager):
    def _create_user(self, username, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username and password.
        """
        now = timezone.now()
        if not username:
            raise ValueError('The given username must be set')
        user = self.model(username=username,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, password=None, **extra_fields):
        return self._create_user(username, password, False, False,
                                 **extra_fields)

    def create_superuser(self, username, password, **extra_fields):
        return self._create_user(username, password, True, True,
                                 **extra_fields)

    def get_by_confirmed_or_primary_email(self, email):
        q = Q(useremail__email=email) & (Q(useremail__confirmed=True) | Q(useremail__primary=True))
        return self.filter(q).prefetch_related('useremail_set').get()

    def get_by_email(self, email):
        return self.filter(useremail__email=email).prefetch_related('useremail_set').get()


def get_applicationrole_ids(user_id, filter=None):
    approles1 = ApplicationRole.objects.filter(user__id=user_id).only("id").values_list('id', flat=True)
    approles2 = ApplicationRole.objects.filter(roleprofile__user__id=user_id).only("id").values_list('id', flat=True)
    if filter is not None:
        approles1 = approles1.filter(filter)
        approles2 = approles2.filter(filter)
    # to get a list of distinct values, we create first a set and then a list
    return list(set(chain(approles1, approles2)))


def generate_filename(instance, filename):
    return u'image/%s/%s' % (instance.uuid.hex, get_filename(filename.encode('ascii', 'replace')))


class User(AbstractBaseUser, PermissionsMixin):
    MAX_PICTURE_SIZE = 5242880  # 5 MB
    GENDER_CHOICES = [
        ('m', _('male')),
        ('f', _('female'))
    ]
    username = models.CharField(_('username'), max_length=30, unique=True, help_text=_('Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.'),
                                validators=[validators.RegexValidator(re.compile(r"^[\w.@+-]+$", flags=re.UNICODE), _('Enter a valid username.'), 'invalid')])
    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False, help_text=_('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(_('active'), default=True, db_index=True, help_text=_('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    # extension
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=True)
    organisations = models.ManyToManyField(Organisation, verbose_name=_('organisations'), blank=True)

apps/sso/accounts/views/onetimemessage.py
# -*- coding: utf-8 -*-
import logging

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.utils.decorators import method_decorator

from sso.accounts.models import OneTimeMessage

logger = logging.getLogger(__name__)


class OneTimeMessageView(DetailView):
    model = OneTimeMessage
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            raise PermissionDenied()
        
        self.object.delete()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

apps/sso/accounts/templates/accounts/application/add_user_done.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Add User' %}{% endblock %}

{% block left_content %}{% include 'include/_navigation.html' with active_navigation="add_user" %}{% endblock left_content %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
        <li class="active">{% trans 'Add User' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}
    <h1>{% trans 'User added successfully' %}</h1>
    <div class="alert alert-success">
        <strong>{% trans 'A new User was created.' %}</strong><br>
        {% trans 'The new user got an email with instructions for setting a password.' %}<br>
    </div>

    <table class="table">
        <tbody>
        <tr>
            <th>{% trans 'Name' %}:</th>
            <td>{{ new_user.username }}</td>
        </tr>
        <tr>
            <th>{% trans 'First name' %}:</th>
            <td>{{ new_user.first_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'Last name' %}:</th>
            <td>{{ new_user.last_name }}</td>
        </tr>
        <tr>
            <th>{% trans 'Email' %}:</th>
            <td>{{ new_user.primary_email }}</td>
        </tr>
        <tr>
            <th>{% trans 'Organisations' %}:</th>
            <td>{% for organisation in new_user.organisations.all %}{{ organisation }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
        </tr>
        {% for role_profile in new_user.role_profiles.all %}
            <tr>
                <th>{% if forloop.first %}{% trans 'Role profiles' %}: {% endif %}</th>
                <td>{{ role_profile }}</td>
            </tr>
        {% endfor %}
        {% for application_role in new_user.application_roles.all %}
            <tr>
                <th>{% if forloop.first %}{% trans 'Application roles' %}: {% endif %}</th>
                <td>{{ application_role }}</td>
            </tr>
        {% endfor %}
        <tr>
            <th>{% trans 'Notes' %}:</th>
            <td>{{ new_user.notes }}</td>
        </tr>
        </tbody>
    </table>
    {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
    <a class="btn btn-default" href="{% url 'accounts:update_user' new_user.uuid.hex %}{% if redirect_uri %}?redirect_uri={{ redirect_uri }}{% endif %}">{% trans 'Edit user' %}</a>
    <a class="btn btn-primary" href="{% url 'accounts:add_user' %}{% if redirect_uri %}?redirect_uri={{ redirect_uri }}{% endif %}">{% trans 'Add another user' %}</a>
{% endblock %}

apps/sso/accounts/templates/accounts/application/update_center_form.html
{% extends "base_form.html" %}
{% load i18n admin_static %}
{% load thumbnail %}

{% block title %}{% trans 'Change User' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
        <li class="active">{% trans 'Change User' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post" data-active="{{ active }}">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="">
            <h3>{{ title }} - {{ form.user.first_name }} {{ form.user.last_name }}</h3>

            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                        {% trans "Please correct the errors below." %}{% endif %}
                </div>
            {% endif %}
        </div>

        <ul class="nav nav-tabs dwbn-nav-tabs" id="myTab">
            <li class="{% if not active or active == "object" %}active{% endif %}">
                <a data-toggle="tab"
                   href="#object">{% trans 'User data' %}</a>
            </li>
            <li><a data-toggle="tab" href="#app_roles">{{ form.application_roles.label }}</a></li>
            <li><a data-toggle="tab" href="#notes">{{ form.notes.label }}</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane {% if not active or active == "object" %}active{% endif %}" id="object">
                {% if not form.user.is_active %}
                    {% include 'include/_static_field.html' with field=form.status extra_class="bg-danger" %}
                {% endif %}
                {% include 'include/_field.html' with field=form.account_type %}
                {% include 'include/_field.html' with field=form.username %}
                {% include 'include/_field.html' with field=form.organisation %}
                {% include 'include/_field.html' with field=form.email %}
                {% include 'accounts/includes/_profiles_field.html' with field=form.role_profiles %}
            </div>
            <div class="tab-pane" id="app_roles">
                {% with field=form.application_roles %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="dwbn-form-control_lg">
                            {{ field }}{% if field.help_text or field.errors %}
                                <span class="help-inline">{{ field.help_text }} {% for error in field.errors %}
                                    {{ error }} {% endfor %}</span>{% endif %}
                        </div>
                    </div>
                {% endwith %}
            </div>
            <div class="tab-pane" id="notes">
                {% with field=form.notes %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="dwbn-form-control_lg">
                            {{ field }}{% if field.help_text or field.errors %}
                                <span class="help-inline">{{ field.help_text }} {% for error in field.errors %}
                                    {{ error }} {% endfor %}</span>{% endif %}
                        </div>
                    </div>
                {% endwith %}
            </div>

        </div>
        <!-- /.tab-content -->

        <div class="form-group">
            <div class="dwbn-form-control_lg">
                {% if form.user.is_active %}
                    <button type="submit" class="btn btn-danger" name="_deactivate">{% trans 'Block User' %}</button>
                {% else %}
                    <button type="submit" class="btn btn-success" name="_activate">{% trans 'Activate User' %}</button>
                {% endif %}
                {% if perms.accounts.delete_user and not form.user.is_active %}
                    <a class="btn btn-default" href="{% url 'accounts:delete_user' form.user.uuid.hex %}">{% trans 'Delete User' %}</a>
                {% endif %}
                {% if perms.accounts.add_user %}
                    <button type="submit" class="btn btn-default" name="_addanother">{% trans 'Save and add another' %}</button>
                {% endif %}
                {% if not logged_in %}
                    <button type="submit" class="btn btn-default" name="_resend_invitation">{% trans 'Save and resend Invitation Mail' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-default" name="_continue">{% trans 'Save and continue editing' %}</button>
                {% if is_validation_period_active %}
                    <button type="submit" class="btn btn-default" name="_extend_validity">{% trans 'Save and extend validity' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            </div>
        </div>

    </form>
{% endblock %}

apps/sso/accounts/templates/accounts/application/update_user_form.html
{% extends "base_form.html" %}
{% load i18n admin_static %}
{% load thumbnail %}

{% block title %}{% trans 'Change User' %}{% endblock %}

{% block extrascript %}
    {{ media }}
    <script src="{% static "js/formsets-1.2.js" %}"></script>
{% endblock extrascript %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:user_list' %}">{% trans 'User List' %}</a></li>
        <li class="active">{% trans 'Change User' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post" data-active="{{ active }}">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="">
            <h3>{{ title }} - {{ form.user.first_name }} {{ form.user.last_name }}</h3>

            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                        {% trans "Please correct the errors below." %}{% endif %}
                </div>
            {% endif %}
        </div>

        <ul class="nav nav-tabs dwbn-nav-tabs" id="myTab">
            <li class="{% if not active or active == "object" %}active{% endif %}">
                <a data-toggle="tab"
                   href="#object">{% trans 'User data' %}</a>
            </li>
            {% for formset in formsets %}
                <li class="{% if active == formset.prefix %}active{% endif %}">
                    <a data-toggle="tab"
                       href="#{{ formset.prefix }}">{{ formset.form.opts.verbose_name_plural|title }}</a>
                </li>
            {% endfor %}
            <li><a data-toggle="tab" href="#app_roles">{{ form.application_roles.label }}</a></li>
            <li><a data-toggle="tab" href="#notes">{{ form.notes.label }}</a></li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane {% if not active or active == "object" %}active{% endif %}" id="object">
                {% if not form.user.is_active %}
                    {% include 'include/_static_field.html' with field=form.status extra_class="bg-danger" %}
                {% endif %}
                {% include 'include/_static_picture_field.html' with field=form.user.picture %}
                {% include 'include/_field.html' with field=form.username %}
                {% if is_validation_period_active %}
                    {% include 'include/_static_field.html' with field=form.valid_until %}
                {% endif %}
                {% include 'include/_field.html' with field=form.first_name %}
                {% include 'include/_field.html' with field=form.last_name %}
                {% include 'include/_field.html' with field=form.gender %}
                {% include 'include/_field.html' with field=form.dob %}
                {% include 'include/_field.html' with field=form.organisations %}
                {% include 'include/_user_field.html' with field=form.created_by_user %}

                {% include 'accounts/includes/_profiles_field.html' with field=form.role_profiles %}

                {% if perms.registration.change_registrationprofile %}
                    {% with registrationprofile=form.user.registrationprofile %}
                        {% if registrationprofile %}
                            <div class="form-group">
                                <label class="control-label"></label>

                                <div class="dwbn-form-control">
                                    <a href="{% url 'registration:update_user_registration' registrationprofile.pk %}">{% trans 'Registration' %}</a>
                                </div>
                            </div>
                        {% endif %}
                    {% endwith %}
                {% endif %}

            </div>
            <div class="tab-pane" id="app_roles">
                {% include 'accounts/includes/_app_roles_field.html' with field=form.application_roles %}
            </div>
            <div class="tab-pane" id="notes">
                {% with field=form.notes %}
                    <div class="form-group {% if field.errors %}has-error{% endif %}">
                        <div class="dwbn-form-control_lg">
                            {{ field }}{% if field.help_text or field.errors %}
                                <span class="help-inline">{{ field.help_text }} {% for error in field.errors %}
                                    {{ error }} {% endfor %}</span>{% endif %}
                        </div>
                    </div>
                {% endwith %}
            </div>
            {% for formset in formsets %}
                <div class="tab-pane {% if active == formset.prefix %}active{% endif %}" id="{{ formset.prefix }}">
                    {% include formset.form.template %}
                </div>
            {% endfor %}

        </div>
        <!-- /.tab-content -->

        <div class="form-group">
            <div class="dwbn-form-control_lg">
                {% if form.user.is_active %}
                    <button type="submit" class="btn btn-danger" name="_deactivate">{% trans 'Block User' %}</button>
                {% else %}
                    <button type="submit" class="btn btn-success" name="_activate">{% trans 'Activate User' %}</button>
                {% endif %}
                {% if perms.accounts.delete_user and not form.user.is_active %}
                    <a class="btn btn-default" href="{% url 'accounts:delete_user' form.user.uuid.hex %}">{% trans 'Delete User' %}</a>
                {% endif %}
                {% if perms.accounts.add_user %}
                    <button type="submit" class="btn btn-default" name="_addanother">{% trans 'Save and add another' %}</button>
                {% endif %}
                {% if not logged_in %}
                    <button type="submit" class="btn btn-default" name="_resend_invitation">{% trans 'Save and resend Invitation Mail' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-default" name="_continue">{% trans 'Save and continue editing' %}</button>
                {% if is_validation_period_active %}
                    <button type="submit" class="btn btn-default" name="_extend_validity">{% trans 'Save and extend validity' %}</button>
                {% endif %}
                <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
            </div>
        </div>

    </form>
{% endblock %}