apps/sso/organisations/urls.py
from django.conf.urls import url
import views
from views import region, country
 
urlpatterns = [
    url(r'^$', views.OrganisationList.as_view(), name='organisation_list'),
    url(r'^export.csv$', views.OrganisationList.as_view(export=True, filename="organisations.csv", content_type='text/csv;charset=utf-8;'), name='organisation_list_csv'),
    url(r'^export.txt$', views.OrganisationList.as_view(export=True, content_type='text;charset=utf-8;'), name='organisation_list_txt'),
    url(r'^me/$', views.MyOrganisationDetailView.as_view(), name='my_organisation_detail'),
    url(r'^(?P<uuid>[a-z0-9]{32})/$', views.OrganisationDetailView.as_view(), name='organisation_detail'),
    url(r'^(?P<uuid>[a-z0-9]{32})/update/$', views.OrganisationUpdateView.as_view(), name='organisation_update'),
    url(r'^(?P<uuid>[a-z0-9]{32})/delete/$', views.OrganisationDeleteView.as_view(), name='organisation_delete'),
    url(r'^(?P<uuid>[a-z0-9]{32})/picture/$', views.OrganisationPictureUpdateView.as_view(), name='organisation_picture_update'),
    url(r'^add/$', views.OrganisationCreateView.as_view(), name='organisation_create'),
    url(r'^region/$', region.AdminRegionList.as_view(), name='adminregion_list'), 
    url(r'^region/(?P<uuid>[a-z0-9]{32})/$', region.AdminRegionDetailView.as_view(), name='adminregion_detail'),
    url(r'^region/(?P<uuid>[a-z0-9]{32})/update/$', region.AdminRegionUpdateView.as_view(), name='adminregion_update'),
    url(r'^region/add/$', region.AdminRegionCreateView.as_view(), name='adminregion_create'),
    url(r'^country/$', country.OrganisationCountryList.as_view(), name='organisationcountry_list'), 
    url(r'^country/(?P<uuid>[a-z0-9]{32})/$', country.OrganisationCountryDetailView.as_view(), name='organisationcountry_detail'),
    url(r'^country/(?P<uuid>[a-z0-9]{32})/update/$', country.OrganisationCountryUpdateView.as_view(), name='organisationcountry_update'),
    url(r'^country/add/$', country.OrganisationCountryCreateView.as_view(), name='organisationcountry_create'),
]

apps/sso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import javascript_catalog
from django.conf.urls.static import static
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.registration.sites import RegistrationSite
from sso.admin import sso_admin_site
from sso.views import home
from sso.oauth2.views import openid_configuration

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

js_info_dict = {
    'packages': ('sso',),
}

urlpatterns = [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^admin/', include(sso_admin_site.urls)),
    url(r'^$', home, name='home'),
    url(r'^privacy/$', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    url(r'^about/$', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    url(r'^accounts/', include('sso.auth.urls', namespace="auth")),
    url(r'^accounts/', include('sso.accounts.urls', namespace="accounts")),
    url(r'^accounts/', include(registration_site.urls)),
    url(r'^organisations/', include('sso.organisations.urls', namespace="organisations")),
    url(r'^emails/', include('sso.emails.urls', namespace="emails")),
    url(r'^oauth2/', include('sso.oauth2.urls', namespace="oauth2")),
    url(r'^.well-known/openid-configuration', openid_configuration, name='openid-configuration'),
    url(r'^api/', include('sso.api.urls', namespace="api")),
    url(r'^chained_filter/(?P<app>l10n)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain, name='chained_filter'),
    url(r'^chained_filter/(?P<app>organisations)/(?P<model>AdminRegion)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain,
        kwargs={'manager': 'active_objects'}, name='chained_filter'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sso/organisations/models.py
import logging
import re

from pytz import timezone
from sorl import thumbnail

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.gis import measure
from django.contrib.gis.db import models as gis_models
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.db import models
from django.utils import six
from django.utils.timezone import localtime, now
from django.utils.translation import pgettext_lazy, ugettext_lazy as _
from l10n.models import Country
from smart_selects.db_fields import ChainedForeignKey
from sso.decorators import memoize
from sso.emails.models import Email, CENTER_EMAIL_TYPE, COUNTRY_EMAIL_TYPE, REGION_EMAIL_TYPE, COUNTRY_GROUP_EMAIL_TYPE
from sso.fields import URLFieldEx
from sso.models import AbstractBaseModel, AddressMixin, PhoneNumberMixin, ensure_single_primary, get_filename

logger = logging.getLogger(__name__)


def is_validation_period_active(organisation):
    if settings.SSO_VALIDATION_PERIOD_IS_ACTIVE:
        if settings.SSO_VALIDATION_PERIOD_IS_ACTIVE_FOR_ALL:
            return True
        else:
            return organisation and organisation.uses_user_activation
    else:
        return False


def is_validation_period_active_for_user(user):
    try:
        user_organisation = user.organisations.first()
    except ObjectDoesNotExist:
        user_organisation = None

    return is_validation_period_active(user_organisation)


class TzWorld(models.Model):
    """
    table from http://efele.net/maps/tz/world/ with timezones and areas
    infos; http://shisaa.jp/postset/postgis-and-postgresql-in-action-timezones.html
    """
    gid = models.AutoField(primary_key=True)
    tzid = models.CharField(max_length=30, blank=True)
    geom = gis_models.PolygonField(blank=True, null=True)
    objects = gis_models.GeoManager()

    class Meta:
        # managed = False
        db_table = 'tz_world'


class CountryGroup(AbstractBaseModel):
    name = models.CharField(_("name"), max_length=255)
    email = models.OneToOneField(Email, verbose_name=_("email address"), blank=True, null=True, limit_choices_to={'email_type': COUNTRY_GROUP_EMAIL_TYPE})
    homepage = models.URLField(_("homepage"), blank=True,)

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Country group')
        verbose_name_plural = _('Country groups')
        ordering = ['name']

    def __unicode__(self):
        return u"%s" % self.name


class OrganisationCountry(AbstractBaseModel):
    country = models.OneToOneField(Country, verbose_name=_("country"), null=True, limit_choices_to={'active': True})
    country_groups = models.ManyToManyField(CountryGroup, blank=True, related_name='countries')
    homepage = models.URLField(_("homepage"), blank=True,)
    email = models.ForeignKey(Email, verbose_name=_("email address"), blank=True, null=True, limit_choices_to={'email_type': COUNTRY_EMAIL_TYPE},
                              on_delete=models.SET_NULL)
    is_active = models.BooleanField(_('active'), default=True, help_text=_('Designates whether this country should be treated as '
                                                                           'active. Unselect this instead of deleting the country.'))

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')
        ordering = ['country']

    def __unicode__(self):
        return u"%s" % self.country

    @models.permalink
    def get_absolute_url(self):
        return 'organisations:organisationcountry_detail', (), {'uuid': self.uuid.hex, }

    @memoize
    def get_last_modified_deep(self):
        last_modified_list = [self.last_modified, self.country.last_modified]

        last_modified = max(last_modified_list)
        return last_modified


class ActiveAdminRegionManager(models.Manager):
    """
    custom manager for using in chained field
    """
    def get_queryset(self):
        return super(ActiveAdminRegionManager, self).get_queryset().filter(is_active=True)


class ExtraManager(models.Model):
    active_objects = ActiveAdminRegionManager()

    class Meta:
        abstract = True


class AdminRegion(AbstractBaseModel, ExtraManager):
    name = models.CharField(_("name"), max_length=255)
    homepage = models.URLField(_("homepage"), blank=True)
    country = models.ForeignKey(Country, verbose_name=_("country"), limit_choices_to={'active': True})
    email = models.OneToOneField(Email, verbose_name=_("email address"), blank=True, null=True, limit_choices_to={'email_type': REGION_EMAIL_TYPE},
                                 on_delete=models.SET_NULL)
    is_active = models.BooleanField(_('active'), default=True, help_text=_('Designates whether this region should be treated as '
                                                                           'active. Unselect this instead of deleting the region.'))
    slug = models.SlugField(_("Slug Name"), blank=True, unique=True,
                            help_text=_("Used for URLs, auto-generated from name if blank"), max_length=255)

    class Meta(AbstractBaseModel.Meta):
        verbose_name = _('Region')
        verbose_name_plural = _('Regions')
        ordering = ['name']

    def __unicode__(self):
        return u"%s" % self.name

    @models.permalink
    def get_absolute_url(self):
        return 'organisations:adminregion_detail', (), {'uuid': self.uuid.hex, }


def get_near_organisations(current_point, distance_from_point=None, qs=None, order=True):
    """
    get all centers with the distance from current_point 
    where the distance is less than distance_from_point
    """
    if current_point is None:
        return Organisation.objects.none()
    if qs is not None:
        organisations = qs
    else:
        organisations = Organisation.objects.all()
    if distance_from_point:
        organisations = organisations.filter(location__distance_lt=(current_point, measure.D(**distance_from_point)))
    organisations = organisations.distance(current_point)
    if order:
        return organisations.distance(current_point).order_by('distance')
    else:
        return organisations.distance(current_point)


class GeoManager(gis_models.GeoManager):
    def get_by_natural_key(self, uuid):
        return self.get(uuid=uuid)


class Organisation(AbstractBaseModel):
    # TODO: make configurable
    CENTER_TYPE_CHOICES = (
        ('1', pgettext_lazy('Organisation Type', 'Center')),
        ('2', pgettext_lazy('Organisation Type', 'Group')),
        ('3', pgettext_lazy('Organisation Type', 'Retreat')),
        ('4', pgettext_lazy('Organisation Type', 'Contact')),
        ('7', pgettext_lazy('Organisation Type', 'Center & Retreat')),
        ('16', pgettext_lazy('Organisation Type', 'Group & Retreat')),
    )
    COORDINATES_TYPE_CHOICES = (
        ('1', _('Unknown')),
        ('2', _('City/Village')),
        ('3', _('Exact')),
        ('4', _('Nearby')),
    )
    _center_type_choices = {}
    for choice in CENTER_TYPE_CHOICES:
        _center_type_choices[choice[0]] = choice[1]

    def center_type_desc(self):
        return self._center_type_choices.get(self.center_type, '')

    _original_location = None

    name = models.CharField(_("name"), max_length=255)
    name_native = models.CharField(_("name in native language"), max_length=255, blank=True)
    country = models.ForeignKey(Country, verbose_name=_("country"), null=True, limit_choices_to={'active': True})
    admin_region = ChainedForeignKey(AdminRegion, chained_field='country', chained_model_field="country", verbose_name=_("admin region"), blank=True, null=True,
                                     limit_choices_to={'is_active': True}) 
    email = models.ForeignKey(Email, verbose_name=_("email address"), blank=True, null=True, limit_choices_to={'email_type': CENTER_EMAIL_TYPE},
                              on_delete=models.SET_NULL)
    slug = models.SlugField(_("Slug Name"), blank=True, unique=True, help_text=_("Used for URLs, auto-generated from name if blank"), max_length=255)
    homepage = models.URLField(_("homepage"), blank=True,)
    google_plus_page = URLFieldEx(domain='plus.google.com', verbose_name=_("Google+ page"), blank=True)
    facebook_page = URLFieldEx(domain='www.facebook.com', verbose_name=_("Facebook page"), blank=True)
    twitter_page = URLFieldEx(domain='twitter.com', verbose_name=_("Twitter page"), blank=True)
    notes = models.TextField(_('notes'), blank=True, max_length=255)
    center_type = models.CharField(_('organisation type'), max_length=2, choices=CENTER_TYPE_CHOICES, db_index=True)
    centerid = models.IntegerField(blank=True, help_text=_("id from the previous center DB (obsolete)"), null=True)
    founded = models.DateField(_("founded"), blank=True, null=True)
    coordinates_type = models.CharField(_('coordinates type'), max_length=1, choices=COORDINATES_TYPE_CHOICES, default='3', db_index=True, blank=True)
    latitude = models.DecimalField(_("latitude"), max_digits=9, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(_("longitude"), max_digits=9, decimal_places=6, blank=True, null=True)
    location = gis_models.PointField(_("location"), geography=True, blank=True, null=True)
    timezone = models.CharField(_('timezone'), blank=True, max_length=254)
    is_active = models.BooleanField(_('active'),
                                    default=True,
                                    help_text=_('Designates whether this organisation should be treated as '
                                                'active. Unselect this instead of deleting organisation.'))
    is_private = models.BooleanField(_("private"), 
                                     help_text=_('Designates whether this organisation data should be treated as private and '
                                                 'only a telephone number should be displayed on public sites.'), 

apps/sso/organisations/templates/organisations/adminregion_detail.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Region Details' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:adminregion_list' %}">{% trans 'Regions' %}</a></li>
        <li class="active">{% trans 'Region Details' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}

    {% block message %}{% endblock %}

    <h3>{{ object.name }}</h3>

    {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
    {% endif %}

    <div class="row">
        <div class="dwbn-label">{% trans 'Name' %}:</div>
        <div class="dwbn-content">{{ object.name }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Country' %}:</div>
        <div class="dwbn-content">{{ object.country }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Homepage' %}:</div>
        <div class="dwbn-content"><a href="{{ object.homepage }}">{{ object.homepage }}</a></div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Active' %}:</div>
        <div class="dwbn-content"><span
                class="glyphicon glyphicon-{% if object.is_active %}ok-sign{% else %}minus-sign{% endif %}"></span>
        </div>
    </div>

    {% if object.email %}
        <div class="row">
            <div class="dwbn-label">{% trans 'Email address' %}:</div>
            <div class="dwbn-content">{{ object.email }}</div>
        </div>
        {% if perms.organisations.change_adminregion and has_region_access %}
            {% for emailforward in  object.email.emailforward_set.all %}
                <div class="row">
                    <div class="dwbn-label">{% trans 'Email forwarding address' %}:</div>
                    <div class="dwbn-content">{{ emailforward }}</div>
                </div>
            {% endfor %}
            {% for emailalias in  object.email.emailalias_set.all %}
                <div class="row">
                    <div class="dwbn-label">{% trans 'Email alias address' %}:</div>
                    <div class="dwbn-content">{{ emailalias }}</div>
                </div>
            {% endfor %}
        {% endif %}
    {% endif %}
    <br>

    <div class="form-group">
        <div class="dwbn-form-control_lg">
            {% block submit_group %}

                {% if perms.organisations.change_adminregion and has_region_access %}
                    <a class="btn btn-primary"
                       href="{% url 'organisations:adminregion_update' object.uuid.hex %}">{% trans 'Update' %}</a>
                {% endif %}

            {% endblock %}
        </div>
    </div>

{% endblock %}

apps/sso/organisations/templates/organisations/organisation_confirm_delete.html
{% extends "organisations/organisation_detail.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete Organisation' %}{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'organisations:organisation_list' %}">{% trans 'Organisations' %}</a></li>
    <li class="active">{% trans 'Delete Organisation' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block message %}
<div class="alert alert-danger">
{% trans "Please confirm deleting this organisation" %}
</div>
{% endblock %}


{% block submit_group %}
<form class="form-horizontal" method="post">{% csrf_token %}  
	<button type="submit" class="btn btn-danger">{% trans 'Confirm Delete Organisation' %}</button>
	<a class="btn btn-primary" href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{% trans 'Cancel' %}</a>
</form>
{% endblock %}

apps/sso/organisations/templates/organisations/organisation_form.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Organisation Details' %}{% endblock %}

{% block extrascript %}{{ media }}
    <script src="{% url 'jsi18n' %}"></script>
{% endblock extrascript %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:organisation_list' %}">{% trans 'Organisations' %}</a></li>
        <li><a href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{{ object.name }}</a></li>
        <li class="active">{% trans 'Update Organisation' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post" data-active="{{ active }}">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}
        {#<input class="hidden" name="redirect_uri" value="{{ redirect_uri }}"/>#}

        <div class="">
            <h3>{{ object.get_center_type_display }} {{ object.name }}</h3>

            {% if messages %}{% for message in messages %}
                <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
            {% endif %}

            {% if errors %}
                <div class="alert alert-danger">
                    {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
                </div>
            {% endif %}

        </div>

        <ul class="nav nav-tabs dwbn-nav-tabs" id="myTab">
            <li class="{% if not active or active == "object" %}active{% endif %}"><a data-toggle="tab" href="#object">{% trans 'Center Data' %}</a></li>
            {% for formset in formsets %}
                <li class="{% if active == formset.prefix %}active{% endif %}"><a data-toggle="tab" href="#{{ formset.prefix }}">{{ formset.form.opts.verbose_name_plural|title }}</a></li>
            {% endfor %}
        </ul>

        <div class="tab-content">
            <div class="tab-pane {% if not active or active == "object" %}active{% endif %}" id="object">
                {% include 'include/_field.html' with field=form.name %}
                {% include 'include/_field.html' with field=form.name_native %}
                {% include 'include/_field.html' with field=form.center_type %}
                {% include 'include/_field.html' with field=form.country %}
                {% include 'include/_field.html' with field=form.admin_region %}
                {% include 'include/_field.html' with field=form.email_value %}
                {% include 'include/_field.html' with field=form.email_forward %} {# for the create form #}
                {% include 'include/_field.html' with field=form.homepage %}
                {% include 'include/_field.html' with field=form.google_plus_page %}
                {% include 'include/_field.html' with field=form.facebook_page %}
                {% include 'include/_field.html' with field=form.twitter_page %}
                {% include 'include/_field.html' with field=form.founded %}
                {% include 'include/_field.html' with field=form.is_private %}
                {% include 'include/_field.html' with field=form.is_active %}
                {% include 'include/_field.html' with field=form.neighbour_distance %}
                {#% include 'include/_field.html' with field=form.can_publish %#}
            </div>

            {% for formset in formsets %}
                <div class="tab-pane {% if active == formset.prefix %}active{% endif %}" id="{{ formset.prefix }}">
                    {% if formset.prefix == 'organisationaddress_set' %}
                        {% include 'include/_static_google_maps_field.html' with field=form.google_maps_url %}
                        {#% include 'include/_static_field.html' with field=form.timezone %#}
                        {% include 'include/_field.html' with field=form.coordinates_type %}
                        {% include 'include/_field.html' with field=form.location %}
                    {% endif %}
                    {% include formset.form.template %}
                </div>
            {% endfor %}

        </div>
        <!-- /.tab-content -->

        <div class="form-group">
            <div class="dwbn-form-submit">
                {% block submit_group %}
                    {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
                    {% if perms.organisations.delete_organisation %}
                        <a class="btn btn-default" href="{% url 'organisations:organisation_delete' object.uuid.hex %}">{% trans 'Delete Organisation' %}</a>
                    {% endif %}
                    <button type="submit" class="btn btn-default" name="_continue">{% trans 'Save and continue editing' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                {% endblock submit_group %}
            </div>
        </div>
    </form>
{% endblock %}

apps/sso/organisations/templates/organisations/organisation_picture_update_form.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Organisation Pictures' %}{% endblock %}

{% block extrascript %}{{ media }}
<script src="{% url 'jsi18n' %}"></script>
{% endblock extrascript %}


{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li><a href="{% url 'organisations:organisation_list' %}">{% trans 'Organisations' %}</a></li>
    <li><a href="{% url 'organisations:organisation_detail' object.uuid.hex %}">{{ object.name }}</a></li>
    <li class="active">{% trans 'Update Picture' %}</li>
</ol> 
{% endblock breadcrumb %}

{% block form %}
<form class="form-horizontal" enctype="multipart/form-data" method="post" >{% csrf_token %}
    {# Include the hidden fields in the form #}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}    
    
    <div class="">
        <h3>{{ object.get_center_type_display }} {{ object.name }}</h3>

        {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
        {% endif %}
        
        {% if errors %}
        <div class="alert alert-danger">
            {% if errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
        </div>
        {% endif %}
        
    </div>

    {% for formset in formsets %}
        {% include formset.form.template %}
    {% endfor %}

    <div class="form-group">
        <div class="dwbn-form-submit">
            {% block submit_group %}
			<button type="submit" class="btn btn-default" name="_continue" >{% trans 'Save and continue editing' %}</button>
			<button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
			{% endblock submit_group %}
		</div>
	</div>
</form>
{% endblock %}

apps/sso/organisations/templates/organisations/organisationcountry_detail.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Country Details' %}{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'organisations:organisationcountry_list' %}">{% trans 'Countries' %}</a></li>
        <li class="active">{% trans 'Country Details' %}</li>
    </ol>
{% endblock breadcrumb %}


{% block form %}

    {% block message %}{% endblock %}

    <h3>{{ object.country }}</h3>

    {% if messages %}{% for message in messages %}
        <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
    {% endif %}


    <div class="row">
        <div class="dwbn-label">{% trans 'Country' %}:</div>
        <div class="dwbn-content">{{ object.country }}</div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Homepage' %}:</div>
        <div class="dwbn-content"><a href="{{ object.homepage }}">{{ object.homepage }}</a></div>
    </div>
    <div class="row">
        <div class="dwbn-label">{% trans 'Active' %}:</div>
        <div class="dwbn-content"><span
                class="glyphicon glyphicon-{% if object.is_active %}ok-sign{% else %}minus-sign{% endif %}"></span>
        </div>
    </div>

    <div class="row">
        <div class="dwbn-label">{% trans 'Email address' %}:</div>
        <div class="dwbn-content">{{ object.email|default_if_none:"" }}</div>
    </div>

    <div class="row">
        <div class="dwbn-label">{% trans 'Organisations' %}:</div>
        <div class="dwbn-content"><a href="{% url 'organisations:organisation_list'  %}?country={{ object.country.pk }}">{% trans 'Organisations' %}</a></div>
    </div>

    {% if perms.organisations.change_organisationcountry and has_country_access %}
        {% for emailforward in  object.email.emailforward_set.all %}
            <div class="row">
                <div class="dwbn-label">{% trans 'Email forwarding address' %}:</div>
                <div class="dwbn-content">{{ emailforward }}</div>
            </div>
        {% endfor %}
        {% for emailalias in  object.email.emailalias_set.all %}
            <div class="row">
                <div class="dwbn-label">{% trans 'Email alias address' %}:</div>
                <div class="dwbn-content">{{ emailalias }}</div>
            </div>
        {% endfor %}

        <div class="row">
            <div class="dwbn-label">{% trans 'Country Groups' %}:</div>
            <div class="dwbn-content">
                <ul>
                    {% for group in object.country_groups.all %}
                        <li>{{ group }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    <br>

    <div class="form-group">
        <div class="dwbn-form-control_lg">
            {% block submit_group %}

                {% if perms.organisations.change_organisationcountry and has_country_access %}
                    <a class="btn btn-primary"
                       href="{% url 'organisations:organisationcountry_update' object.uuid.hex %}">{% trans 'Update' %}</a>
                {% endif %}

            {% endblock %}
        </div>
    </div>

{% endblock %}