apps/sso/accounts/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from .views import application
from .views import onetimemessage
from .views import password_change, password_change_done, logout, profile, contact, delete_profile
from .views import password_reset, password_reset_confirm, password_reset_done, password_reset_complete
from .views import emails, confirm_email, password_create_confirm, password_create_complete
from .views import organisation

urlpatterns = [
    url(r'^$', application.UserList.as_view(), name='user_list'),
    url(r'^me/$', profile, name='profile'),
    url(r'^add/$', application.add_user, name='add_user'),
    url(r'^add/done/(?P<uuid>[^/]+)/$', application.add_user_done, name="add_user_done"),
    url(r'^(?P<uuid>[a-z0-9]{32})/$', application.update_user, name="update_user"),
    url(r'^(?P<uuid>[a-z0-9]{32})/delete/$', application.UserDeleteView.as_view(), name="delete_user"),
    url(r'^app_admin/$', application.AppAdminUserList.as_view(), name='app_admin_user_list'),
    url(r'^app_admin/(?P<uuid>[a-z0-9]{32})/', application.app_admin_update_user, name="app_admin_update_user"),
    url(r'^logout/$', logout, name='logout'),
    url(r'^contact/$', contact, name='contact'),
    url(r'^contact_thanks/$', TemplateView.as_view(template_name="accounts/contact_thanks.html"), name='contact_thanks'),
    url(r'^email/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', confirm_email, name='confirm_email'),
    url(r'^emails/$', emails, name='emails'),
    url(r'^profile/delete/$', delete_profile, name='delete_profile'),
    url(r'^password_change/$', password_change, name='password_change'),
    url(r'^password_change/done/$', password_change_done, name='password_change_done'),
    url(r'^password_reset/$', password_reset, name='password_reset'),
    url(r'^password_reset/done/$', password_reset_done, name='password_reset_done'),
    url(r'^password_resend/done/$', TemplateView.as_view(template_name="accounts/password_resend_done.html"), name='password_resend_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', password_reset_complete, name='password_reset_complete'),
    url(r'^create/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_create_confirm, name='password_create_confirm'),
    url(r'^create/done/(?P<uidb64>[0-9A-Za-z_\-]+)/$', password_create_complete, name='password_create_complete'),
    url(r'^organisation_change/(?P<pk>\d+)/$', organisation.OrganisationChangeDetailView.as_view(), name='organisationchange_detail'),
    url(r'^organisation_change/me/$', organisation.OrganisationChangeUpdateView.as_view(), name='organisationchange_me'),
    url(r'^organisation_change/$', organisation.OrganisationChangeList.as_view(), name='organisationchange_list'),
    url(r'^organisation_change/(?P<pk>\d+)/accept/$', organisation.OrganisationChangeAcceptView.as_view(), name='organisationchange_accept'),
    url(r'^messages/(?P<uuid>[^/]+)/$', onetimemessage.OneTimeMessageView.as_view(), name="view_message"),
]

apps/sso/auth/urls.py
from django.conf.urls import url
from sso.auth.views import LoginView, TokenView
from sso.auth.views.profile import ProfileView, TOTPSetup, PhoneSetupView, AddPhoneView, AddU2FView

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^token/(?P<device_id>[\d]+)/(?P<user_data>[^/]+)/$', TokenView.as_view(), name='token'),
    url(r'^profile/$', ProfileView.as_view(), name='profile'),
    url(r'^profile/totp_setup/$', TOTPSetup.as_view(), name='profile_totp_setup'),
    url(r'^profile/add_phone/$', AddPhoneView.as_view(), name='add_phone'),
    url(r'^profile/phone_setup/(?P<sms_device_id>[\d]+)/$', PhoneSetupView.as_view(), name='phone_setup'),
    url(r'^profile/u2f/add_device/$', AddU2FView.as_view(), name='u2f_add_device'),
]

apps/sso/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.views.generic import RedirectView, TemplateView
from django.views.i18n import javascript_catalog
from django.conf.urls.static import static
from smart_selects.views import filterchain
from sso.accounts.forms import UserSelfRegistrationForm2
from sso.registration.sites import RegistrationSite
from sso.admin import sso_admin_site
from sso.views import home
from sso.oauth2.views import openid_configuration

registration_site = RegistrationSite(form_cls=UserSelfRegistrationForm2)

js_info_dict = {
    'packages': ('sso',),
}

urlpatterns = [
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='jsi18n'),
    url(r'^admin/', include(sso_admin_site.urls)),
    url(r'^$', home, name='home'),
    url(r'^privacy/$', TemplateView.as_view(template_name="privacy.html"), name='privacy'),
    url(r'^about/$', RedirectView.as_view(url=settings.SSO_ABOUT, permanent=False), name='about'),
    url(r'^accounts/', include('sso.auth.urls', namespace="auth")),
    url(r'^accounts/', include('sso.accounts.urls', namespace="accounts")),
    url(r'^accounts/', include(registration_site.urls)),
    url(r'^organisations/', include('sso.organisations.urls', namespace="organisations")),
    url(r'^emails/', include('sso.emails.urls', namespace="emails")),
    url(r'^oauth2/', include('sso.oauth2.urls', namespace="oauth2")),
    url(r'^.well-known/openid-configuration', openid_configuration, name='openid-configuration'),
    url(r'^api/', include('sso.api.urls', namespace="api")),
    url(r'^chained_filter/(?P<app>l10n)/(?P<model>[\w\-]+)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain, name='chained_filter'),
    url(r'^chained_filter/(?P<app>organisations)/(?P<model>AdminRegion)/(?P<field>[\w\-]+)/(?P<value>[\w\-]+)/$', filterchain,
        kwargs={'manager': 'active_objects'}, name='chained_filter'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/sso/accounts/views/application.py
# -*- coding: utf-8 -*-
from datetime import timedelta
import logging
from django.utils.six.moves.urllib.parse import urlunsplit

from django.db.models.expressions import F
from django.conf import settings
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required, user_passes_test
from django.views.generic import DeleteView
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import get_object_or_404
from django.utils.encoding import force_text
from sso.oauth2.models import allowed_hosts
from sso.auth.decorators import admin_login_required
from sso.views import main
from sso.views.generic import ListView
from sso.accounts.models import User, UserEmail, ApplicationRole
from sso.accounts.email import send_account_created_email
from sso.organisations.models import Organisation, is_validation_period_active
from sso.accounts.forms import UserAddForm, UserProfileForm, UserEmailForm, AppAdminUserProfileForm, CenterProfileForm
from sso.forms.helpers import ChangedDataList, log_change, ErrorList
from filter import AdminRegionFilter, ApplicationRoleFilter, CenterFilter, CountryFilter, IsActiveFilter, RoleProfileFilter, UserSearchFilter
from sso.views.main import OrderByWithNulls
from sso.utils.url import get_safe_redirect_uri


logger = logging.getLogger(__name__)
    

class UserDeleteView(DeleteView):
    slug_field = slug_url_kwarg = 'uuid'
    model = get_user_model()
    success_url = reverse_lazy('accounts:user_list')
    
    @method_decorator(admin_login_required)
    @method_decorator(permission_required('accounts.delete_user', raise_exception=True))
    def dispatch(self, request, *args, **kwargs):
        # additionally check if the user is admin of the user       
        if not request.user.has_user_access(kwargs.get('uuid')):
            raise PermissionDenied
        return super(UserDeleteView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        context['cancel_url'] = reverse('accounts:update_user', args=[self.object.uuid.hex])
        # the user is initialized from the ViewClass with the user to delete
        # so reinitialize it with the request user
        context['user'] = self.request.user
        return context


class LastLogin(object):
    verbose_name = _('last login')
    sortable = True
    ordering_field = OrderByWithNulls(F('last_login'))

    def __str__(self):
        return 'last_login'


class OrganisationField(object):
    verbose_name = _('organisation')
    sortable = True
    ordering_field = 'organisations'

    def __str__(self):
        return 'organisation'


class ValidUntil(object):
    verbose_name = _('valid until')
    sortable = True
    ordering_field = OrderByWithNulls(F('valid_until'))

    def __str__(self):
        return 'valid_until'


class UserList(ListView):

    template_name = 'accounts/application/user_list.html'
    model = get_user_model()
    IS_ACTIVE_CHOICES = (('1', _('Active Users')), ('2', _('Inactive Users')))

    @method_decorator(admin_login_required)
    @method_decorator(user_passes_test(lambda u: u.is_user_admin))
    def dispatch(self, request, *args, **kwargs):
        return super(UserList, self).dispatch(request, *args, **kwargs)

    @property
    def list_display(self):
        if settings.SSO_VALIDATION_PERIOD_IS_ACTIVE:
            return ['username', 'picture', 'last_name', _('primary email'), OrganisationField(),LastLogin(), 'date_joined', ValidUntil()]
        else:
            return ['username', 'picture', 'last_name', _('primary email'), OrganisationField(),LastLogin(), 'date_joined']

    def get_queryset(self):
        """
        Get the list of items for this view. This must be an iterable, and may
        be a queryset (in which qs-specific behavior will be enabled).
        """
        user = self.request.user

        qs = super(UserList, self).get_queryset().only('uuid', 'last_login', 'username', 'first_name', 'last_name', 'date_joined', 'picture', 'valid_until')\
            .prefetch_related('useremail_set', 'organisations')
        qs = user.filter_administrable_users(qs)
            
        self.cl = main.ChangeList(self.request, self.model, self.list_display, default_ordering=[OrderByWithNulls(F('last_login'), descending=True)])
        # apply filters
        qs = UserSearchFilter().apply(self, qs) 
        qs = CountryFilter().apply(self, qs)
        qs = AdminRegionFilter().apply(self, qs)
        qs = CenterFilter().apply(self, qs)
        qs = ApplicationRoleFilter().apply(self, qs)
        qs = RoleProfileFilter().apply(self, qs)
        qs = IsActiveFilter().apply(self, qs, default='1')
        
        # Set ordering.
        ordering = self.cl.get_ordering(self.request, qs)
        qs = qs.order_by(*ordering).distinct()
        return qs

    def get_context_data(self, **kwargs):
        user = self.request.user
        headers = list(self.cl.result_headers())
        num_sorted_fields = 0
        for h in headers:
            if h['sortable'] and h['sorted']:
                num_sorted_fields += 1
        
        countries = user.get_administrable_user_countries()
        country_filter = CountryFilter().get(self, countries)

        centers = Organisation.objects.none()
        application_roles = user.get_administrable_application_roles()
        role_profiles = user.get_administrable_role_profiles()
        admin_regions = user.get_administrable_user_regions()

        if self.country:
            centers = user.get_administrable_user_organisations().filter(country=self.country)
            if self.admin_region:
                centers = centers.filter(admin_region=self.admin_region)
            if self.center:
                application_roles = application_roles.filter(user__organisations__in=[self.center]).distinct() 
                role_profiles = role_profiles.filter(user__organisations__in=[self.center]).distinct()
            else:
                application_roles = application_roles.filter(user__organisations__in=centers).distinct() 
                role_profiles = role_profiles.filter(user__organisations__in=centers).distinct()

        admin_region_filter = AdminRegionFilter().get(self, admin_regions)
        center_filter = CenterFilter().get(self, centers)
        application_role_filter = ApplicationRoleFilter().get(self, application_roles)
        role_profile_filter = RoleProfileFilter().get(self, role_profiles)

        filters = [country_filter, admin_region_filter, center_filter, role_profile_filter, application_role_filter]
        if user.is_user_admin:
            filters += [IsActiveFilter().get(self)]

        context = {
            'result_headers': headers,
            'num_sorted_fields': num_sorted_fields,
            'search_var': main.SEARCH_VAR,
            'page_var': main.PAGE_VAR,
            'query': self.request.GET.get(main.SEARCH_VAR, ''),
            'cl': self.cl,
            'filters': filters,
            'is_active': self.is_active,
            'sso_validation_period_is_active': settings.SSO_VALIDATION_PERIOD_IS_ACTIVE
        }
        context.update(kwargs)
        return super(UserList, self).get_context_data(**context)
    

class AppAdminUserList(ListView):
    template_name = 'accounts/application/app_admin_user_list.html'
    model = get_user_model()

    @method_decorator(admin_login_required)
    @method_decorator(user_passes_test(lambda u: u.is_app_admin()))
    def dispatch(self, request, *args, **kwargs):
        return super(AppAdminUserList, self).dispatch(request, *args, **kwargs)

    @property
    def list_display(self):
        return ['username', 'picture', 'last_name', _('primary email'), OrganisationField(),LastLogin(), 'date_joined']

    def get_queryset(self):
        """
        Get the list of items for this view. This must be an iterable, and may
        be a queryset (in which qs-specific behavior will be enabled).
        """
        user = self.request.user

        qs = super(AppAdminUserList, self).get_queryset().only('uuid', 'last_login', 'username', 'first_name', 'last_name', 'date_joined',
                                                               'picture', 'valid_until')\
            .prefetch_related('useremail_set', 'organisations')
        qs = user.filter_administrable_app_admin_users(qs)

        self.cl = main.ChangeList(self.request, self.model, self.list_display, default_ordering=[OrderByWithNulls(F('last_login'), descending=True)])
        # apply filters
        qs = UserSearchFilter().apply(self, qs)
        qs = CountryFilter().apply(self, qs)
        qs = AdminRegionFilter().apply(self, qs)
        qs = CenterFilter().apply(self, qs)
        qs = ApplicationRoleFilter().apply(self, qs)
        qs = RoleProfileFilter().apply(self, qs)
        qs = IsActiveFilter().apply(self, qs, default='1')

        # Set ordering.
        ordering = self.cl.get_ordering(self.request, qs)
        qs = qs.order_by(*ordering).distinct()
        return qs

    def get_context_data(self, **kwargs):
        user = self.request.user
        headers = list(self.cl.result_headers())
        num_sorted_fields = 0
        for h in headers:
            if h['sortable'] and h['sorted']:
                num_sorted_fields += 1


apps/sso/accounts/views/onetimemessage.py
# -*- coding: utf-8 -*-
import logging

from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from django.utils.decorators import method_decorator

from sso.accounts.models import OneTimeMessage

logger = logging.getLogger(__name__)


class OneTimeMessageView(DetailView):
    model = OneTimeMessage
    slug_field = 'uuid'
    slug_url_kwarg = 'uuid'

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            raise PermissionDenied()
        
        self.object.delete()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

apps/sso/accounts/templates/accounts/contact_thanks.html
{% extends "base_form.html" %}
{% load i18n %}

{% block title %}{{ brand }} | {% trans 'Contact Information' %}{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Feedback' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block form %}
<h1>{% trans 'Feedback' %}</h1>
<p>{% trans "Thank you for your message." %}</p>


{% endblock %}

apps/sso/accounts/templates/accounts/delete_profile_form.html
{% extends "base_form.html" %}
{% load i18n static %}

{% block title %}{% trans 'Profile' %}{% endblock %}

{% block left_content %}{% include 'include/_navigation.html' with active_navigation="profile" %}{% endblock left_content %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'User profile' %}</li>
</ol> 
{% endblock breadcrumb %}


{% block form %}
<form class="form-horizontal" method="post">{% csrf_token %}	
    <div class="">
	    <h3>{% trans 'Delete Profile' %}</h3>
		<p>{% trans "Do you want to delete your account?" %}</p>
		
	    {% if messages %}{% for message in messages %}
	       <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
	    {% endif %}
		
		
	    {% if form.errors %}
	        <div class="alert alert-danger">
	        {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
	        </div>
	    {% endif %}
    </div>
    <div class="form-group">
        <div class="dwbn-form-control_lg">
	        <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
            &nbsp;{% trans 'or' %}&nbsp; <a class="btn btn-default" href="{% url 'accounts:profile' %}">{% trans 'Cancel' %}</a>            
	    </div>
    </div>
	
	<script type="text/javascript">document.getElementById("id_first_name").focus();</script>
	
</form>
{% endblock %}

apps/sso/accounts/templates/accounts/logged_out.html
{% extends "base_site.html" %}
{% load i18n %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<div class="alert alert-danger">
{% blocktrans %}To protect your privacy:<br>If you are using a shared/public computer, please close all open browser windows and start a new session by opening a new browser window.{% endblocktrans  %}
</div>

<p><a href="{% url 'auth:login' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

apps/sso/accounts/templates/accounts/organisationchange_accept.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Accept Organisation Change' %}{% endblock %}

{% block extrascript %}{{ media }}{% endblock extrascript %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:organisationchange_list' %}">{% trans 'Organisation Changes' %}</a></li>
        <li class="active">{% trans 'Accept Organisation Change' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <h3>{% trans 'Process Organisation Change' %}</h3>

        <p>{% trans "Please accept or deny the organisation change request." %}</p>

        {% if messages %}{% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
        {% endif %}

        {% if form.errors %}
            <div class="alert alert-danger">
                {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </div>
        {% endif %}

        <div class="form-group">
            <label class="control-label">{% trans 'First name' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.first_name }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Last name' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.last_name }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Email address' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.primary_email }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Phone number' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.primary_phone }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'Previous organisation' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.user.organisations.all.first|default_if_none:"" }}</p></div>
        </div>

        <div class="form-group">
            <label class="control-label">{% trans 'New organisation' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.organisation }}</p></div>
        </div>
        <div class="form-group">
            <label class="control-label">{% trans 'Reason' %}</label>

            <div class="dwbn-form-control"><p class="form-control-static">{{ organisationchange.reason }}</p></div>
        </div>

        <div class="form-group">
            <div class="dwbn-form-control_lg">
                {% block submit_group %}
                    <button type="submit" class="btn btn-danger" name="_delete">{% trans 'Deny change' %}</button>
                    <button type="submit" class="btn btn-primary">{% trans 'Accept change' %}</button>
                {% endblock submit_group %}
            </div>
        </div>
    </form>
{% endblock %}

apps/sso/accounts/templates/accounts/organisationchange_form.html
{% extends "base_form.html" %}
{% load i18n admin_static %}

{% block title %}{% trans 'Organisation Change Details' %}{% endblock %}

{% block extrascript %}{{ media }}{% endblock extrascript %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
        <li><a href="{% url 'accounts:profile' %}">{% trans 'My Account' %}</a></li>
        <li class="active">{% trans 'Update My Organisation' %}</li>
    </ol>
{% endblock breadcrumb %}

{% block form %}
    <form class="form-horizontal" method="post">{% csrf_token %}
        {# Include the hidden fields in the form #}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <h3>{% trans 'Update My Organisation' %}</h3>

        <p>{% trans "Please select the organisation you moved to and insert a reason text." %}</p>

        {% if messages %}{% for message in messages %}
            <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
        {% endif %}

        {% if form.errors %}
            <div class="alert alert-danger">
                {% if form.errors|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
            </div>
        {% endif %}


        {% include 'include/_field.html' with field=form.organisation %}
        {% include 'include/_field.html' with field=form.reason %}

        <div class="form-group">
            <div class="dwbn-form-submit">
                {% block submit_group %}
                    {% if redirect_uri %}<a class="btn btn-default" href="{{ redirect_uri }}">{% trans 'Back' %}</a>{% endif %}
                    {% if form.instance.pk %}<button type="submit" class="btn btn-danger" name="_delete">{% trans 'Cancel change of organisation' %}</button>{% endif %}
                    <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
                    <button type="submit" class="btn btn-default" name="_continue">{% trans 'Save and continue editing' %}</button>
                {% endblock submit_group %}
            </div>
        </div>
    </form>
{% endblock %}

apps/sso/accounts/templates/accounts/organisationchange_list.html
{% extends 'base_site.html' %}
{% load i18n list tz static %}

{% block title %}{% trans 'Organisation Change Request List' %}{% endblock %}

{% block nav_accounts_user_list_class %}active{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Organisation Changes' %}</li>
</ol> 
{% endblock breadcrumb %}
    
    
{% block content %}
<div class="row">
	<div class="col-sm-12">
	    {% if messages %}{% for message in messages %}
	       <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</div>{% endfor %}
	    {% endif %}
	</div>
</div><!-- /.row -->

<div class="row dwbn-filter-row">
	<div class="col-sm-3">
	   {% include 'include/_search_form.html' %}
    </div>
	<div class="col-sm-9">
        {% for filter in filters %}{% if filter %} 
        {% include filter.template_name with filter=filter %}
        {% endif %}{% endfor %}
    </div><!-- /.col-sm-9 -->
</div>

<main>
    <div class="col-sm-12 table-responsive">
	   <table class="table table-bordered table-striped">
	       {% include "include/table_header.html" %}
	       <tbody>
	           {% for object in object_list %}
	           <tr> 
	               <td><a class="" href="{% url 'accounts:organisationchange_accept' object.pk %}">{{ object.user.username }}</a></td>
	               <td>{{ object.user.organisations.first|default_if_none:"" }}</td>
	               <td>{{ object.organisation }}</td>
	               <td>{{ object.reason }}</td>
	               <td>{{ object.user.primary_email|default_if_none:"" }}</td>
	               <td>{{ object.last_modified|utc|date:"Y-m-d H:i" }}</td>
	           </tr>
	           {% endfor %}
	       </tbody>
	   </table>
	   {% if is_paginated %}{% pagination page_obj cl %}{% endif %}
    </div>
</main>
{% endblock content %}

apps/sso/accounts/templates/accounts/password_resend_done.html
{% extends "centered_form.html" %}
{% load i18n %}

{% block title %}{% trans 'Password resend successful' %}{% endblock %}

{% block form %}

<h1>{% trans 'Password resend successful' %}</h1>

<p>{% trans "We've emailed you your password to the email address you submitted. You should be receiving it shortly." %}</p>

{% endblock %}

apps/sso/accounts/templates/accounts/password_reset_complete.html
{% extends "centered_form.html" %}
{% load i18n %}

{% block title %}{% trans 'Password reset complete' %}{% endblock %}

{% block form %}

<h1>{% trans 'Password reset complete' %}</h1>

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}